version: "3.9"

services:
  backend:
    build: ./backend
    container_name: django-backend
    restart: unless-stopped
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      # Можно добавить другие переменные
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3          # ← важно! сохраняем базу
      - ./backend/static:/app/static                  # для collectstatic
      - ./backend/media:/app/media                    # если используешь media-файлы
      - ./models:/app/models:rw
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000

  nginx:
    build: ./nginx
    container_name: nginx-frontend
    restart: unless-stopped
    ports:
      - "80:80"          # основной сайт
      # - "443:443"      # раскомментируй позже для HTTPS
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html/frontend:ro
      - ./backend/static:/usr/share/nginx/html/static:ro
      - ./backend/media:/usr/share/nginx/html/media:ro